# Generated by Django 5.2.4 on 2025-07-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('server', '伺服器'), ('desktop', '桌上型電腦'), ('laptop', '筆記型電腦'), ('mobile', '行動裝置'), ('network', '網路設備'), ('printer', '印表機'), ('monitor', '顯示器'), ('storage', '儲存設備'), ('other', '其他')], max_length=50, unique=True, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('depreciation_years', models.IntegerField(default=5, verbose_name='折舊年限')),
            ],
            options={
                'verbose_name': '資產類別',
                'verbose_name_plural': '資產類別',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供應商名稱')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('website', models.URLField(blank=True, verbose_name='網站')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='資產標籤')),
                ('name', models.CharField(max_length=100, verbose_name='資產名稱')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型號')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序號')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='採購日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='採購價格')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='發票號碼')),
                ('warranty_start_date', models.DateField(blank=True, null=True, verbose_name='保固開始日期')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='保固結束日期')),
                ('warranty_provider', models.CharField(blank=True, max_length=100, verbose_name='保固提供商')),
                ('status', models.CharField(choices=[('active', '使用中'), ('inactive', '閒置'), ('maintenance', '維修中'), ('retired', '已報廢'), ('lost', '遺失')], default='active', max_length=20, verbose_name='狀態')),
                ('condition', models.CharField(choices=[('excellent', '極佳'), ('good', '良好'), ('fair', '普通'), ('poor', '差'), ('broken', '損壞')], default='good', max_length=20, verbose_name='狀況')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='規格')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcategory', verbose_name='資產類別')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '硬體資產',
                'verbose_name_plural': '硬體資產',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=100, verbose_name='軟體名稱')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('license_type', models.CharField(choices=[('perpetual', '永久授權'), ('subscription', '訂閱授權'), ('volume', '大量授權'), ('oem', 'OEM授權'), ('trial', '試用版'), ('free', '免費軟體')], max_length=20, verbose_name='授權類型')),
                ('license_key', models.CharField(blank=True, max_length=200, verbose_name='授權金鑰')),
                ('total_licenses', models.IntegerField(default=1, verbose_name='總授權數')),
                ('used_licenses', models.IntegerField(default=0, verbose_name='已使用授權數')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='採購日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='採購價格')),
                ('annual_maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='年度維護費用')),
                ('status', models.CharField(choices=[('active', '使用中'), ('expired', '已過期'), ('unused', '未使用'), ('retired', '已停用')], default='active', max_length=20, verbose_name='狀態')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('assigned_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='分配用戶')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '軟體授權',
                'verbose_name_plural': '軟體授權',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True, verbose_name='申請單號')),
                ('title', models.CharField(max_length=200, verbose_name='申請標題')),
                ('description', models.TextField(verbose_name='申請描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已批准'), ('rejected', '已拒絕'), ('purchased', '已採購'), ('received', '已收貨'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=10, verbose_name='優先級')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='預估費用')),
                ('budget_code', models.CharField(blank=True, max_length=20, verbose_name='預算代碼')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='審核日期')),
                ('approval_notes', models.TextField(blank=True, verbose_name='審核備註')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='實際費用')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='採購日期')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='預計交貨日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='審核人')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor', verbose_name='供應商')),
            ],
            options={
                'verbose_name': '採購申請',
                'verbose_name_plural': '採購申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', '預防性維護'), ('corrective', '修復性維護'), ('upgrade', '升級'), ('inspection', '檢查')], max_length=20, verbose_name='維修類型')),
                ('description', models.TextField(verbose_name='維修描述')),
                ('status', models.CharField(choices=[('scheduled', '已排程'), ('in_progress', '進行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='狀態')),
                ('scheduled_date', models.DateTimeField(verbose_name='排程日期')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='費用')),
                ('notes', models.TextField(blank=True, verbose_name='維修備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.hardwareasset', verbose_name='資產')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='技術人員')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.vendor', verbose_name='外包廠商')),
            ],
            options={
                'verbose_name': '維修記錄',
                'verbose_name_plural': '維修記錄',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
