# Generated by Django 5.2.4 on 2025-07-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='類別名稱'),
        ),
    ]
