# Generated by Django 5.2.4 on 2025-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwareasset',
            name='category',
            field=models.CharField(max_length=50, verbose_name='資產類別'),
        ),
    ]
