# Generated by Django 5.2.4 on 2025-07-26 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='規則名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('rule_type', models.CharField(choices=[('allow', '允許'), ('deny', '拒絕'), ('drop', '丟棄')], default='allow', max_length=10, verbose_name='動作')),
                ('status', models.CharField(choices=[('active', '啟用'), ('inactive', '停用'), ('testing', '測試中')], default='active', max_length=10, verbose_name='狀態')),
                ('priority', models.IntegerField(default=100, help_text='數字越小優先級越高', verbose_name='優先級')),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='空白表示任何IP', null=True, verbose_name='來源IP')),
                ('source_port', models.CharField(blank=True, help_text='可使用範圍如 1000-2000 或逗號分隔', max_length=20, verbose_name='來源埠')),
                ('destination_ip', models.GenericIPAddressField(blank=True, help_text='空白表示任何IP', null=True, verbose_name='目標IP')),
                ('destination_port', models.CharField(blank=True, help_text='可使用範圍如 80,443,8000-9000', max_length=20, verbose_name='目標埠')),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('any', '任何協定')], default='any', max_length=10, verbose_name='協定')),
                ('direction', models.CharField(choices=[('inbound', '入站'), ('outbound', '出站'), ('both', '雙向')], default='inbound', max_length=10, verbose_name='方向')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_system_rule', models.BooleanField(default=False, help_text='系統規則無法刪除', verbose_name='系統規則')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='命中次數')),
                ('last_hit', models.DateTimeField(blank=True, null=True, verbose_name='最後命中時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '防火牆規則',
                'verbose_name_plural': '防火牆規則',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FirewallRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('hit', '命中'), ('block', '阻擋'), ('allow', '允許')], max_length=10, verbose_name='日誌類型')),
                ('source_ip', models.GenericIPAddressField(verbose_name='來源IP')),
                ('destination_ip', models.GenericIPAddressField(verbose_name='目標IP')),
                ('source_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='來源埠')),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='目標埠')),
                ('protocol', models.CharField(max_length=10, verbose_name='協定')),
                ('packet_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='封包大小')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='時間')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.firewallrule', verbose_name='相關規則')),
            ],
            options={
                'verbose_name': '防火牆日誌',
                'verbose_name_plural': '防火牆日誌',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='憑證名稱')),
                ('domain', models.CharField(max_length=255, verbose_name='網域名稱')),
                ('cert_type', models.CharField(choices=[('domain', '網域憑證'), ('wildcard', '萬用憑證'), ('ev', 'EV憑證'), ('ov', 'OV憑證'), ('dv', 'DV憑證')], max_length=20, verbose_name='憑證類型')),
                ('issuer', models.CharField(max_length=100, verbose_name='發行機構')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='序號')),
                ('subject', models.TextField(verbose_name='主體資訊')),
                ('san_domains', models.JSONField(blank=True, default=list, help_text='主體別名中的其他網域', verbose_name='SAN網域')),
                ('issued_date', models.DateTimeField(verbose_name='發行日期')),
                ('expires_date', models.DateTimeField(verbose_name='到期日期')),
                ('status', models.CharField(choices=[('valid', '有效'), ('expired', '已過期'), ('expiring', '即將過期'), ('revoked', '已撤銷')], default='valid', max_length=20, verbose_name='狀態')),
                ('certificate_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='憑證檔案')),
                ('private_key_file', models.FileField(blank=True, upload_to='private_keys/', verbose_name='私鑰檔案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('remind_days_before', models.PositiveIntegerField(default=30, verbose_name='提前提醒天數')),
                ('last_reminder_sent', models.DateTimeField(blank=True, null=True, verbose_name='最後提醒時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': 'SSL憑證',
                'verbose_name_plural': 'SSL憑證',
                'ordering': ['expires_date'],
            },
        ),
        migrations.CreateModel(
            name='VPNConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='連線名稱')),
                ('connection_type', models.CharField(choices=[('openvpn', 'OpenVPN'), ('ipsec', 'IPSec'), ('pptp', 'PPTP'), ('l2tp', 'L2TP'), ('wireguard', 'WireGuard')], max_length=20, verbose_name='VPN類型')),
                ('server_address', models.CharField(max_length=255, verbose_name='伺服器位址')),
                ('local_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='本地IP')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='遠端IP')),
                ('status', models.CharField(choices=[('connected', '已連線'), ('disconnected', '未連線'), ('connecting', '連線中'), ('error', '錯誤')], default='disconnected', max_length=20, verbose_name='狀態')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='連線時間')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='斷線時間')),
                ('bytes_sent', models.BigIntegerField(default=0, verbose_name='傳送位元組')),
                ('bytes_received', models.BigIntegerField(default=0, verbose_name='接收位元組')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'VPN連線',
                'verbose_name_plural': 'VPN連線',
                'ordering': ['-connected_at', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='firewallrule',
            index=models.Index(fields=['status', 'priority'], name='security_fi_status_b574e8_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrule',
            index=models.Index(fields=['source_ip'], name='security_fi_source__bbbf1a_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrule',
            index=models.Index(fields=['destination_ip'], name='security_fi_destina_d514be_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrulelog',
            index=models.Index(fields=['-timestamp'], name='security_fi_timesta_81f033_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrulelog',
            index=models.Index(fields=['rule', '-timestamp'], name='security_fi_rule_id_4bb6e2_idx'),
        ),
        migrations.AddIndex(
            model_name='firewallrulelog',
            index=models.Index(fields=['source_ip', '-timestamp'], name='security_fi_source__f807a5_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['expires_date'], name='security_ss_expires_abf38e_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['domain'], name='security_ss_domain_2ab10c_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['status'], name='security_ss_status_b46773_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnection',
            index=models.Index(fields=['user', 'status'], name='security_vp_user_id_e2607b_idx'),
        ),
        migrations.AddIndex(
            model_name='vpnconnection',
            index=models.Index(fields=['-connected_at'], name='security_vp_connect_cb9640_idx'),
        ),
    ]
